# http://www.appveyor.com/docs/appveyor-yml

notifications:
  - provider: Email
    to:
      - b.stanimirov@abv.bg
    on_build_status_changed: true
    on_build_failure: true
    on_build_success: false

clone_depth: 5
branches:
  only:
    - master
    - dev

matrix:
  fast_finish: false

environment:
  matrix:
  - gen: "Visual Studio 14 2015"
  - gen: "Visual Studio 15 2017"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
  - if not exist vcbuild_x86 mkdir vcbuild_x86
  - cd vcbuild_x86
  - cmake .. -G "%gen%"
  - msbuild dynamix.sln /p:Configuration=Debug;Platform=Win32 /maxcpucount /verbosity:minimal
  - ctest -C Debug --output-on-failure
  - msbuild dynamix.sln /p:Configuration=Release;Platform=Win32 /maxcpucount /verbosity:minimal
  - ctest -C Release --output-on-failure
  - cd ..
  - if not exist vcbuild_x64 mkdir vcbuild_x64
  - cd vcbuild_x64
  - cmake .. -G "%gen% Win64"
  - msbuild dynamix.sln /p:Configuration=Debug;Platform=x64 /maxcpucount /verbosity:minimal
  - ctest -C Debug --output-on-failure
  - msbuild dynamix.sln /p:Configuration=Release;Platform=x64 /maxcpucount /verbosity:minimal
  - ctest -C Release --output-on-failure
  - cd ..
  - if not exist vcbuild_cc mkdir vcbuild_cc
  - cd vcbuild_cc
  - cmake .. -DDYNAMIX_BUILD_PERF=0 -DDYNAMIX_BUILD_EXAMPLES=0 -DDYNAMIX_BUILD_TUTORIALS=0 -DDYNAMIX_BUILD_SCRATCH=0 -DDYNAMIX_CUSTOM_CONFIG_FILE="\"%cd%\..\..\..\test\custom_config\custom_config.hpp\"" -G "%gen% Win64"
  - msbuild dynamix.sln /p:Configuration=Debug;Platform=x64 /maxcpucount /verbosity:minimal
  - ctest -C Debug --output-on-failure
  - msbuild dynamix.sln /p:Configuration=Release;Platform=x64 /maxcpucount /verbosity:minimal
  - ctest -C Release --output-on-failure
  - cd ..
# static analysis
  #~ - if "%gen%" == "Visual Studio 15 2017" mkdir vcbuild_analysis
  #~ - if "%gen%" == "Visual Studio 15 2017" cd vcbuild_analysis
  #~ - if "%gen%" == "Visual Studio 15 2017" cmake .. -G "%gen% Win64"
  #~ - if "%gen%" == "Visual Studio 15 2017" msbuild dynamix.sln /p:Configuration=Debug;Platform=x64 /maxcpucount /p:RunCodeAnalysis=true /p:CodeAnalysisTreatWarningsAsErrors=true
  #~ - if "%gen%" == "Visual Studio 15 2017" cd ..
